name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Cache Rust dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-docs-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-docs-
          ${{ runner.os }}-cargo-
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2-dev pkg-config
    
    - name: Install mdbook
      run: |
        if ! command -v mdbook &> /dev/null; then
          cargo install mdbook
        else
          echo "mdbook already installed: $(mdbook --version)"
        fi
    
    - name: Generate Rust documentation
      run: |
        cargo doc --no-deps --document-private-items
        echo '<meta http-equiv="refresh" content="0; url=soma_player">' > target/doc/index.html
    
    - name: Generate mdBook documentation
      run: |
        cd docs
        mdbook build
    
    - name: Prepare documentation site
      run: |
        mkdir -p site
        cp -r target/doc site/api
        cp -r docs/book site/guide
        cat > site/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Soma Player Documentation</title>
            <style>
                body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 2rem; background: #f5f5f5; }
                .container { max-width: 800px; margin: 0 auto; background: white; padding: 2rem; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
                h1 { color: #333; border-bottom: 2px solid #007acc; padding-bottom: 0.5rem; }
                .docs-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 1.5rem; margin-top: 2rem; }
                .doc-card { border: 1px solid #ddd; border-radius: 6px; padding: 1.5rem; background: #fafafa; }
                .doc-card h2 { margin-top: 0; color: #007acc; }
                .doc-card a { color: #007acc; text-decoration: none; font-weight: 500; }
                .doc-card a:hover { text-decoration: underline; }
            </style>
        </head>
        <body>
            <div class="container">
                <h1>🎵 Soma Player Documentation</h1>
                <p>Welcome to the Soma Player documentation. Choose the documentation type that best fits your needs:</p>
                <div class="docs-grid">
                    <div class="doc-card">
                        <h2>📚 API Documentation</h2>
                        <p>Comprehensive technical documentation generated from the source code, including all modules, functions, and types.</p>
                        <a href="api/">View API Documentation →</a>
                    </div>
                    <div class="doc-card">
                        <h2>📖 User Guide</h2>
                        <p>Extended user guide with installation instructions, configuration options, and usage examples.</p>
                        <a href="guide/">View User Guide →</a>
                    </div>
                </div>
            </div>
        </body>
        </html>
        EOF
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-docs
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Setup Pages
      uses: actions/configure-pages@v5
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
