name: Generate SBOM

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run weekly to keep SBOM updated
    - cron: '0 0 * * 0'

permissions:
  contents: read

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Rust dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-sbom-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-sbom-

    - name: Install system dependencies (Linux)
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2-dev pkg-config

    - name: Install SBOM tools
      run: |
        if ! command -v cargo-cyclonedx &> /dev/null; then
          cargo install cargo-cyclonedx
        else
          echo "cargo-cyclonedx already installed"
        fi

    - name: Generate SBOM
      run: |
        chmod +x generate-sbom.sh
        ./generate-sbom.sh

    - name: Upload SBOM artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sbom-${{ github.sha }}
        path: sbom/
        retention-days: 90

    - name: Upload SBOM to release (if tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          sbom/sbom-cyclonedx.json
          sbom/sbom-cyclonedx.xml
          sbom/security-audit.txt
          sbom/README.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
